name: myenv
channels:
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pip:
      - tensorflow==2.19.0
      - scikit-learn==1.6.1
      - numpy==2.1.3
      - pandas==2.2.3
      - matplotlib==3.10.1
      - joblib==1.4.2